[2021-03-08 12:13:47,669] {scheduler_job.py:182} INFO - Started process (PID=2440) to work on /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
[2021-03-08 12:13:47,669] {scheduler_job.py:629} INFO - Processing file /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py for tasks to queue
[2021-03-08 12:13:47,670] {logging_mixin.py:104} INFO - [2021-03-08 12:13:47,670] {dagbag.py:448} INFO - Filling up the DagBag from /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
[2021-03-08 12:13:48,119] {logging_mixin.py:104} INFO - [2021-03-08 12:13:48,118] {dagbag.py:305} ERROR - Failed to import: /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
Traceback (most recent call last):
  File "/Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py", line 6, in <module>
    import db as db
ModuleNotFoundError: No module named 'db'
[2021-03-08 12:13:48,119] {scheduler_job.py:641} WARNING - No viable dags retrieved from /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
[2021-03-08 12:13:48,206] {scheduler_job.py:190} INFO - Processing /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py took 0.538 seconds
[2021-03-08 12:14:51,727] {scheduler_job.py:182} INFO - Started process (PID=2524) to work on /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
[2021-03-08 12:14:51,727] {scheduler_job.py:629} INFO - Processing file /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py for tasks to queue
[2021-03-08 12:14:51,728] {logging_mixin.py:104} INFO - [2021-03-08 12:14:51,728] {dagbag.py:448} INFO - Filling up the DagBag from /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
[2021-03-08 12:14:51,992] {logging_mixin.py:104} INFO - [2021-03-08 12:14:51,991] {dagbag.py:305} ERROR - Failed to import: /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
Traceback (most recent call last):
  File "/Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py", line 6, in <module>
    import db as db
ModuleNotFoundError: No module named 'db'
[2021-03-08 12:14:51,992] {scheduler_job.py:641} WARNING - No viable dags retrieved from /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
[2021-03-08 12:14:52,056] {scheduler_job.py:190} INFO - Processing /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py took 0.330 seconds
[2021-03-08 12:15:52,495] {scheduler_job.py:182} INFO - Started process (PID=2598) to work on /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
[2021-03-08 12:15:52,496] {scheduler_job.py:629} INFO - Processing file /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py for tasks to queue
[2021-03-08 12:15:52,496] {logging_mixin.py:104} INFO - [2021-03-08 12:15:52,496] {dagbag.py:448} INFO - Filling up the DagBag from /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
[2021-03-08 12:15:52,770] {logging_mixin.py:104} INFO - [2021-03-08 12:15:52,770] {dagbag.py:305} ERROR - Failed to import: /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
Traceback (most recent call last):
  File "/Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py", line 6, in <module>
    import db as db
ModuleNotFoundError: No module named 'db'
[2021-03-08 12:15:52,770] {scheduler_job.py:641} WARNING - No viable dags retrieved from /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
[2021-03-08 12:15:52,836] {scheduler_job.py:190} INFO - Processing /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py took 0.341 seconds
[2021-03-08 12:16:52,882] {scheduler_job.py:182} INFO - Started process (PID=2670) to work on /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
[2021-03-08 12:16:52,883] {scheduler_job.py:629} INFO - Processing file /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py for tasks to queue
[2021-03-08 12:16:52,883] {logging_mixin.py:104} INFO - [2021-03-08 12:16:52,883] {dagbag.py:448} INFO - Filling up the DagBag from /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
[2021-03-08 12:16:53,139] {logging_mixin.py:104} INFO - [2021-03-08 12:16:53,138] {dagbag.py:305} ERROR - Failed to import: /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
Traceback (most recent call last):
  File "/Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py", line 6, in <module>
    import db as db
ModuleNotFoundError: No module named 'db'
[2021-03-08 12:16:53,139] {scheduler_job.py:641} WARNING - No viable dags retrieved from /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
[2021-03-08 12:16:53,206] {scheduler_job.py:190} INFO - Processing /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py took 0.325 seconds
[2021-03-08 12:18:05,191] {scheduler_job.py:182} INFO - Started process (PID=2773) to work on /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
[2021-03-08 12:18:05,192] {scheduler_job.py:629} INFO - Processing file /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py for tasks to queue
[2021-03-08 12:18:05,192] {logging_mixin.py:104} INFO - [2021-03-08 12:18:05,192] {dagbag.py:448} INFO - Filling up the DagBag from /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
[2021-03-08 12:18:05,532] {logging_mixin.py:104} INFO - [2021-03-08 12:18:05,532] {dagbag.py:305} ERROR - Failed to import: /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
Traceback (most recent call last):
  File "/Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py", line 6, in <module>
    import db as db
ModuleNotFoundError: No module named 'db'
[2021-03-08 12:18:05,533] {scheduler_job.py:641} WARNING - No viable dags retrieved from /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
[2021-03-08 12:18:05,607] {scheduler_job.py:190} INFO - Processing /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py took 0.417 seconds
[2021-03-08 12:19:28,279] {scheduler_job.py:182} INFO - Started process (PID=2875) to work on /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
[2021-03-08 12:19:28,280] {scheduler_job.py:629} INFO - Processing file /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py for tasks to queue
[2021-03-08 12:19:28,281] {logging_mixin.py:104} INFO - [2021-03-08 12:19:28,281] {dagbag.py:448} INFO - Filling up the DagBag from /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
[2021-03-08 12:19:28,884] {logging_mixin.py:104} INFO - [2021-03-08 12:19:28,883] {dagbag.py:305} ERROR - Failed to import: /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
Traceback (most recent call last):
  File "/Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py", line 6, in <module>
    import db as db
ModuleNotFoundError: No module named 'db'
[2021-03-08 12:19:28,885] {scheduler_job.py:641} WARNING - No viable dags retrieved from /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
[2021-03-08 12:19:29,083] {scheduler_job.py:190} INFO - Processing /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py took 0.806 seconds
[2021-03-08 12:20:18,552] {scheduler_job.py:182} INFO - Started process (PID=2926) to work on /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
[2021-03-08 12:20:18,553] {scheduler_job.py:629} INFO - Processing file /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py for tasks to queue
[2021-03-08 12:20:18,554] {logging_mixin.py:104} INFO - [2021-03-08 12:20:18,554] {dagbag.py:448} INFO - Filling up the DagBag from /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
[2021-03-08 12:20:18,819] {logging_mixin.py:104} INFO - [2021-03-08 12:20:18,818] {dagbag.py:305} ERROR - Failed to import: /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
Traceback (most recent call last):
  File "/Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py", line 6, in <module>
    import db as db
ModuleNotFoundError: No module named 'db'
[2021-03-08 12:20:18,819] {scheduler_job.py:641} WARNING - No viable dags retrieved from /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
[2021-03-08 12:20:18,888] {scheduler_job.py:190} INFO - Processing /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py took 0.337 seconds
[2021-03-08 12:21:27,909] {scheduler_job.py:182} INFO - Started process (PID=3016) to work on /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
[2021-03-08 12:21:27,910] {scheduler_job.py:629} INFO - Processing file /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py for tasks to queue
[2021-03-08 12:21:27,910] {logging_mixin.py:104} INFO - [2021-03-08 12:21:27,910] {dagbag.py:448} INFO - Filling up the DagBag from /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
[2021-03-08 12:21:28,166] {logging_mixin.py:104} INFO - [2021-03-08 12:21:28,165] {dagbag.py:305} ERROR - Failed to import: /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
Traceback (most recent call last):
  File "/Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py", line 6, in <module>
    import db as db
ModuleNotFoundError: No module named 'db'
[2021-03-08 12:21:28,166] {scheduler_job.py:641} WARNING - No viable dags retrieved from /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
[2021-03-08 12:21:28,238] {scheduler_job.py:190} INFO - Processing /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py took 0.330 seconds
[2021-03-08 12:22:38,814] {scheduler_job.py:182} INFO - Started process (PID=3111) to work on /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
[2021-03-08 12:22:38,815] {scheduler_job.py:629} INFO - Processing file /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py for tasks to queue
[2021-03-08 12:22:38,815] {logging_mixin.py:104} INFO - [2021-03-08 12:22:38,815] {dagbag.py:448} INFO - Filling up the DagBag from /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
[2021-03-08 12:22:39,065] {logging_mixin.py:104} INFO - [2021-03-08 12:22:39,065] {dagbag.py:305} ERROR - Failed to import: /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
Traceback (most recent call last):
  File "/Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py", line 6, in <module>
    import db as db
ModuleNotFoundError: No module named 'db'
[2021-03-08 12:22:39,066] {scheduler_job.py:641} WARNING - No viable dags retrieved from /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
[2021-03-08 12:22:39,130] {scheduler_job.py:190} INFO - Processing /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py took 0.317 seconds
[2021-03-08 12:23:39,137] {scheduler_job.py:182} INFO - Started process (PID=3178) to work on /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
[2021-03-08 12:23:39,137] {scheduler_job.py:629} INFO - Processing file /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py for tasks to queue
[2021-03-08 12:23:39,138] {logging_mixin.py:104} INFO - [2021-03-08 12:23:39,138] {dagbag.py:448} INFO - Filling up the DagBag from /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
[2021-03-08 12:23:39,374] {logging_mixin.py:104} INFO - [2021-03-08 12:23:39,374] {dagbag.py:305} ERROR - Failed to import: /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
Traceback (most recent call last):
  File "/Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py", line 6, in <module>
    import db as db
ModuleNotFoundError: No module named 'db'
[2021-03-08 12:23:39,375] {scheduler_job.py:641} WARNING - No viable dags retrieved from /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
[2021-03-08 12:23:39,436] {scheduler_job.py:190} INFO - Processing /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py took 0.301 seconds
[2021-03-08 12:24:38,062] {scheduler_job.py:182} INFO - Started process (PID=3250) to work on /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
[2021-03-08 12:24:38,063] {scheduler_job.py:629} INFO - Processing file /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py for tasks to queue
[2021-03-08 12:24:38,064] {logging_mixin.py:104} INFO - [2021-03-08 12:24:38,063] {dagbag.py:448} INFO - Filling up the DagBag from /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
[2021-03-08 12:24:38,467] {logging_mixin.py:104} INFO - [2021-03-08 12:24:38,466] {dagbag.py:305} ERROR - Failed to import: /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
Traceback (most recent call last):
  File "/Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py", line 6, in <module>
    import db as db
ModuleNotFoundError: No module named 'db'
[2021-03-08 12:24:38,467] {scheduler_job.py:641} WARNING - No viable dags retrieved from /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
[2021-03-08 12:24:38,547] {scheduler_job.py:190} INFO - Processing /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py took 0.486 seconds
[2021-03-08 12:25:28,589] {scheduler_job.py:182} INFO - Started process (PID=3360) to work on /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
[2021-03-08 12:25:28,590] {scheduler_job.py:629} INFO - Processing file /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py for tasks to queue
[2021-03-08 12:25:28,590] {logging_mixin.py:104} INFO - [2021-03-08 12:25:28,590] {dagbag.py:448} INFO - Filling up the DagBag from /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
[2021-03-08 12:25:28,909] {logging_mixin.py:104} INFO - [2021-03-08 12:25:28,908] {dagbag.py:305} ERROR - Failed to import: /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
Traceback (most recent call last):
  File "/Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py", line 6, in <module>
    import db as db
ModuleNotFoundError: No module named 'db'
[2021-03-08 12:25:28,909] {scheduler_job.py:641} WARNING - No viable dags retrieved from /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
[2021-03-08 12:25:28,976] {scheduler_job.py:190} INFO - Processing /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py took 0.387 seconds
[2021-03-08 12:26:16,474] {scheduler_job.py:182} INFO - Started process (PID=3478) to work on /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
[2021-03-08 12:26:16,476] {scheduler_job.py:629} INFO - Processing file /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py for tasks to queue
[2021-03-08 12:26:16,476] {logging_mixin.py:104} INFO - [2021-03-08 12:26:16,476] {dagbag.py:448} INFO - Filling up the DagBag from /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
[2021-03-08 12:26:16,932] {logging_mixin.py:104} INFO - [2021-03-08 12:26:16,931] {dagbag.py:305} ERROR - Failed to import: /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
Traceback (most recent call last):
  File "/Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py", line 6, in <module>
    import db as db
ModuleNotFoundError: No module named 'db'
[2021-03-08 12:26:16,932] {scheduler_job.py:641} WARNING - No viable dags retrieved from /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
[2021-03-08 12:26:16,998] {scheduler_job.py:190} INFO - Processing /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py took 0.524 seconds
[2021-03-08 12:26:59,452] {scheduler_job.py:182} INFO - Started process (PID=3602) to work on /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
[2021-03-08 12:26:59,452] {scheduler_job.py:629} INFO - Processing file /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py for tasks to queue
[2021-03-08 12:26:59,453] {logging_mixin.py:104} INFO - [2021-03-08 12:26:59,453] {dagbag.py:448} INFO - Filling up the DagBag from /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
[2021-03-08 12:26:59,724] {logging_mixin.py:104} INFO - [2021-03-08 12:26:59,724] {dagbag.py:305} ERROR - Failed to import: /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
Traceback (most recent call last):
  File "/Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py", line 6, in <module>
    import db as db
ModuleNotFoundError: No module named 'db'
[2021-03-08 12:26:59,725] {scheduler_job.py:641} WARNING - No viable dags retrieved from /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
[2021-03-08 12:26:59,787] {scheduler_job.py:190} INFO - Processing /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py took 0.337 seconds
[2021-03-08 12:28:02,002] {scheduler_job.py:182} INFO - Started process (PID=3684) to work on /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
[2021-03-08 12:28:02,002] {scheduler_job.py:629} INFO - Processing file /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py for tasks to queue
[2021-03-08 12:28:02,003] {logging_mixin.py:104} INFO - [2021-03-08 12:28:02,003] {dagbag.py:448} INFO - Filling up the DagBag from /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
[2021-03-08 12:28:02,275] {logging_mixin.py:104} INFO - [2021-03-08 12:28:02,274] {dagbag.py:305} ERROR - Failed to import: /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
Traceback (most recent call last):
  File "/Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py", line 6, in <module>
    import db as db
ModuleNotFoundError: No module named 'db'
[2021-03-08 12:28:02,275] {scheduler_job.py:641} WARNING - No viable dags retrieved from /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
[2021-03-08 12:28:02,346] {scheduler_job.py:190} INFO - Processing /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py took 0.345 seconds
[2021-03-08 12:28:58,283] {scheduler_job.py:182} INFO - Started process (PID=3755) to work on /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
[2021-03-08 12:28:58,284] {scheduler_job.py:629} INFO - Processing file /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py for tasks to queue
[2021-03-08 12:28:58,284] {logging_mixin.py:104} INFO - [2021-03-08 12:28:58,284] {dagbag.py:448} INFO - Filling up the DagBag from /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
[2021-03-08 12:28:58,519] {logging_mixin.py:104} INFO - [2021-03-08 12:28:58,518] {dagbag.py:305} ERROR - Failed to import: /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
Traceback (most recent call last):
  File "/Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py", line 6, in <module>
    import db as db
ModuleNotFoundError: No module named 'db'
[2021-03-08 12:28:58,519] {scheduler_job.py:641} WARNING - No viable dags retrieved from /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
[2021-03-08 12:28:58,582] {scheduler_job.py:190} INFO - Processing /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py took 0.300 seconds
[2021-03-08 12:29:56,706] {scheduler_job.py:182} INFO - Started process (PID=3824) to work on /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
[2021-03-08 12:29:56,706] {scheduler_job.py:629} INFO - Processing file /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py for tasks to queue
[2021-03-08 12:29:56,707] {logging_mixin.py:104} INFO - [2021-03-08 12:29:56,707] {dagbag.py:448} INFO - Filling up the DagBag from /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
[2021-03-08 12:29:56,956] {logging_mixin.py:104} INFO - [2021-03-08 12:29:56,956] {dagbag.py:305} ERROR - Failed to import: /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
Traceback (most recent call last):
  File "/Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py", line 6, in <module>
    import db as db
ModuleNotFoundError: No module named 'db'
[2021-03-08 12:29:56,956] {scheduler_job.py:641} WARNING - No viable dags retrieved from /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
[2021-03-08 12:29:57,019] {scheduler_job.py:190} INFO - Processing /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py took 0.314 seconds
[2021-03-08 12:31:12,176] {scheduler_job.py:182} INFO - Started process (PID=3905) to work on /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
[2021-03-08 12:31:12,176] {scheduler_job.py:629} INFO - Processing file /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py for tasks to queue
[2021-03-08 12:31:12,177] {logging_mixin.py:104} INFO - [2021-03-08 12:31:12,177] {dagbag.py:448} INFO - Filling up the DagBag from /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
[2021-03-08 12:31:12,587] {logging_mixin.py:104} INFO - [2021-03-08 12:31:12,586] {dagbag.py:305} ERROR - Failed to import: /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
Traceback (most recent call last):
  File "/Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py", line 6, in <module>
    import db as db
ModuleNotFoundError: No module named 'db'
[2021-03-08 12:31:12,587] {scheduler_job.py:641} WARNING - No viable dags retrieved from /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
[2021-03-08 12:31:12,662] {scheduler_job.py:190} INFO - Processing /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py took 0.487 seconds
[2021-03-08 12:32:26,416] {scheduler_job.py:182} INFO - Started process (PID=3989) to work on /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
[2021-03-08 12:32:26,416] {scheduler_job.py:629} INFO - Processing file /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py for tasks to queue
[2021-03-08 12:32:26,417] {logging_mixin.py:104} INFO - [2021-03-08 12:32:26,417] {dagbag.py:448} INFO - Filling up the DagBag from /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
[2021-03-08 12:32:26,652] {logging_mixin.py:104} INFO - [2021-03-08 12:32:26,652] {dagbag.py:305} ERROR - Failed to import: /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
Traceback (most recent call last):
  File "/Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py", line 6, in <module>
    import db as db
ModuleNotFoundError: No module named 'db'
[2021-03-08 12:32:26,652] {scheduler_job.py:641} WARNING - No viable dags retrieved from /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
[2021-03-08 12:32:26,719] {scheduler_job.py:190} INFO - Processing /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py took 0.303 seconds
[2021-03-08 12:33:32,321] {scheduler_job.py:182} INFO - Started process (PID=4067) to work on /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
[2021-03-08 12:33:32,322] {scheduler_job.py:629} INFO - Processing file /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py for tasks to queue
[2021-03-08 12:33:32,322] {logging_mixin.py:104} INFO - [2021-03-08 12:33:32,322] {dagbag.py:448} INFO - Filling up the DagBag from /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
[2021-03-08 12:33:32,612] {scheduler_job.py:639} INFO - DAG(s) dict_keys(['extract_standings']) retrieved from /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
[2021-03-08 12:33:32,644] {logging_mixin.py:104} INFO - [2021-03-08 12:33:32,644] {dag.py:1818} INFO - Sync 1 DAGs
[2021-03-08 12:33:32,648] {logging_mixin.py:104} INFO - [2021-03-08 12:33:32,648] {dag.py:1837} INFO - Creating ORM DAG for extract_standings
[2021-03-08 12:33:32,655] {logging_mixin.py:104} INFO - [2021-03-08 12:33:32,655] {dag.py:2273} INFO - Setting next_dagrun for extract_standings to 2021-01-01T00:00:00+00:00
[2021-03-08 12:33:32,665] {scheduler_job.py:190} INFO - Processing /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py took 0.345 seconds
[2021-03-08 12:34:38,916] {scheduler_job.py:182} INFO - Started process (PID=4147) to work on /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
[2021-03-08 12:34:38,917] {scheduler_job.py:629} INFO - Processing file /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py for tasks to queue
[2021-03-08 12:34:38,917] {logging_mixin.py:104} INFO - [2021-03-08 12:34:38,917] {dagbag.py:448} INFO - Filling up the DagBag from /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
[2021-03-08 12:34:38,919] {logging_mixin.py:104} INFO - [2021-03-08 12:34:38,918] {dagbag.py:305} ERROR - Failed to import: /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
Traceback (most recent call last):
  File "/Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
  File "<frozen importlib._bootstrap_external>", line 916, in get_code
  File "<frozen importlib._bootstrap_external>", line 846, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py", line 6
    import ../db
           ^
SyntaxError: invalid syntax
[2021-03-08 12:34:38,919] {scheduler_job.py:641} WARNING - No viable dags retrieved from /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
[2021-03-08 12:34:38,952] {scheduler_job.py:190} INFO - Processing /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py took 0.037 seconds
[2021-03-08 12:35:48,409] {scheduler_job.py:182} INFO - Started process (PID=4222) to work on /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
[2021-03-08 12:35:48,410] {scheduler_job.py:629} INFO - Processing file /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py for tasks to queue
[2021-03-08 12:35:48,410] {logging_mixin.py:104} INFO - [2021-03-08 12:35:48,410] {dagbag.py:448} INFO - Filling up the DagBag from /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
[2021-03-08 12:35:48,412] {logging_mixin.py:104} INFO - [2021-03-08 12:35:48,411] {dagbag.py:305} ERROR - Failed to import: /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
Traceback (most recent call last):
  File "/Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
  File "<frozen importlib._bootstrap_external>", line 916, in get_code
  File "<frozen importlib._bootstrap_external>", line 846, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py", line 6
    import ../db
           ^
SyntaxError: invalid syntax
[2021-03-08 12:35:48,412] {scheduler_job.py:641} WARNING - No viable dags retrieved from /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
[2021-03-08 12:35:48,447] {scheduler_job.py:190} INFO - Processing /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py took 0.039 seconds
[2021-03-08 12:36:56,742] {scheduler_job.py:182} INFO - Started process (PID=4311) to work on /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
[2021-03-08 12:36:56,743] {scheduler_job.py:629} INFO - Processing file /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py for tasks to queue
[2021-03-08 12:36:56,743] {logging_mixin.py:104} INFO - [2021-03-08 12:36:56,743] {dagbag.py:448} INFO - Filling up the DagBag from /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
[2021-03-08 12:36:56,745] {logging_mixin.py:104} INFO - [2021-03-08 12:36:56,744] {dagbag.py:305} ERROR - Failed to import: /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
Traceback (most recent call last):
  File "/Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
  File "<frozen importlib._bootstrap_external>", line 916, in get_code
  File "<frozen importlib._bootstrap_external>", line 846, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py", line 6
    import ../db
           ^
SyntaxError: invalid syntax
[2021-03-08 12:36:56,745] {scheduler_job.py:641} WARNING - No viable dags retrieved from /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
[2021-03-08 12:36:56,790] {scheduler_job.py:190} INFO - Processing /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py took 0.048 seconds
[2021-03-08 14:17:46,386] {scheduler_job.py:182} INFO - Started process (PID=8115) to work on /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
[2021-03-08 14:17:46,388] {scheduler_job.py:629} INFO - Processing file /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py for tasks to queue
[2021-03-08 14:17:46,388] {logging_mixin.py:104} INFO - [2021-03-08 14:17:46,388] {dagbag.py:448} INFO - Filling up the DagBag from /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
[2021-03-08 14:17:46,615] {scheduler_job.py:639} INFO - DAG(s) dict_keys(['extract_standings']) retrieved from /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
[2021-03-08 14:17:46,619] {logging_mixin.py:104} INFO - [2021-03-08 14:17:46,619] {dag.py:1818} INFO - Sync 1 DAGs
[2021-03-08 14:17:46,643] {logging_mixin.py:104} INFO - [2021-03-08 14:17:46,643] {dag.py:2273} INFO - Setting next_dagrun for extract_standings to 2021-01-01T00:00:00+00:00
[2021-03-08 14:17:46,646] {scheduler_job.py:190} INFO - Processing /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py took 0.260 seconds
[2021-03-08 14:18:18,870] {scheduler_job.py:182} INFO - Started process (PID=8137) to work on /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
[2021-03-08 14:18:18,871] {scheduler_job.py:629} INFO - Processing file /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py for tasks to queue
[2021-03-08 14:18:18,871] {logging_mixin.py:104} INFO - [2021-03-08 14:18:18,871] {dagbag.py:448} INFO - Filling up the DagBag from /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
[2021-03-08 14:18:19,388] {scheduler_job.py:639} INFO - DAG(s) dict_keys(['extract_standings']) retrieved from /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
[2021-03-08 14:18:19,413] {logging_mixin.py:104} INFO - [2021-03-08 14:18:19,413] {dag.py:1818} INFO - Sync 1 DAGs
[2021-03-08 14:18:19,423] {logging_mixin.py:104} INFO - [2021-03-08 14:18:19,423] {dag.py:2273} INFO - Setting next_dagrun for extract_standings to 2021-01-01T00:00:00+00:00
[2021-03-08 14:18:19,428] {scheduler_job.py:190} INFO - Processing /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py took 0.559 seconds
[2021-03-08 14:18:51,779] {scheduler_job.py:182} INFO - Started process (PID=8152) to work on /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
[2021-03-08 14:18:51,779] {scheduler_job.py:629} INFO - Processing file /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py for tasks to queue
[2021-03-08 14:18:51,779] {logging_mixin.py:104} INFO - [2021-03-08 14:18:51,779] {dagbag.py:448} INFO - Filling up the DagBag from /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
[2021-03-08 14:18:52,172] {scheduler_job.py:639} INFO - DAG(s) dict_keys(['extract_standings']) retrieved from /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
[2021-03-08 14:18:52,197] {logging_mixin.py:104} INFO - [2021-03-08 14:18:52,196] {dag.py:1818} INFO - Sync 1 DAGs
[2021-03-08 14:18:52,204] {logging_mixin.py:104} INFO - [2021-03-08 14:18:52,204] {dag.py:2273} INFO - Setting next_dagrun for extract_standings to 2021-01-01T00:00:00+00:00
[2021-03-08 14:18:52,208] {scheduler_job.py:190} INFO - Processing /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py took 0.429 seconds
[2021-03-08 14:46:17,473] {scheduler_job.py:182} INFO - Started process (PID=8610) to work on /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
[2021-03-08 14:46:17,473] {scheduler_job.py:629} INFO - Processing file /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py for tasks to queue
[2021-03-08 14:46:17,474] {logging_mixin.py:104} INFO - [2021-03-08 14:46:17,474] {dagbag.py:448} INFO - Filling up the DagBag from /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
[2021-03-08 14:46:17,854] {scheduler_job.py:639} INFO - DAG(s) dict_keys(['extract_standings']) retrieved from /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
[2021-03-08 14:46:17,879] {logging_mixin.py:104} INFO - [2021-03-08 14:46:17,879] {dag.py:1818} INFO - Sync 1 DAGs
[2021-03-08 14:46:17,888] {logging_mixin.py:104} INFO - [2021-03-08 14:46:17,888] {dag.py:2273} INFO - Setting next_dagrun for extract_standings to 2021-01-01T00:00:00+00:00
[2021-03-08 14:46:17,892] {scheduler_job.py:190} INFO - Processing /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py took 0.420 seconds
[2021-03-08 14:46:49,888] {scheduler_job.py:182} INFO - Started process (PID=8627) to work on /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
[2021-03-08 14:46:49,889] {scheduler_job.py:629} INFO - Processing file /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py for tasks to queue
[2021-03-08 14:46:49,889] {logging_mixin.py:104} INFO - [2021-03-08 14:46:49,889] {dagbag.py:448} INFO - Filling up the DagBag from /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
[2021-03-08 14:46:50,133] {scheduler_job.py:639} INFO - DAG(s) dict_keys(['extract_standings']) retrieved from /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
[2021-03-08 14:46:50,156] {logging_mixin.py:104} INFO - [2021-03-08 14:46:50,156] {dag.py:1818} INFO - Sync 1 DAGs
[2021-03-08 14:46:50,165] {logging_mixin.py:104} INFO - [2021-03-08 14:46:50,165] {dag.py:2273} INFO - Setting next_dagrun for extract_standings to 2021-01-01T00:00:00+00:00
[2021-03-08 14:46:50,168] {scheduler_job.py:190} INFO - Processing /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py took 0.280 seconds
[2021-03-08 14:47:33,888] {scheduler_job.py:182} INFO - Started process (PID=8655) to work on /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
[2021-03-08 14:47:33,888] {scheduler_job.py:629} INFO - Processing file /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py for tasks to queue
[2021-03-08 14:47:33,889] {logging_mixin.py:104} INFO - [2021-03-08 14:47:33,889] {dagbag.py:448} INFO - Filling up the DagBag from /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
[2021-03-08 14:47:34,163] {scheduler_job.py:639} INFO - DAG(s) dict_keys(['extract_standings']) retrieved from /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
[2021-03-08 14:47:34,166] {logging_mixin.py:104} INFO - [2021-03-08 14:47:34,166] {dag.py:1818} INFO - Sync 1 DAGs
[2021-03-08 14:47:34,196] {logging_mixin.py:104} INFO - [2021-03-08 14:47:34,196] {dag.py:2273} INFO - Setting next_dagrun for extract_standings to 2021-01-01T00:00:00+00:00
[2021-03-08 14:47:34,200] {scheduler_job.py:190} INFO - Processing /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py took 0.313 seconds
[2021-03-08 14:48:06,325] {scheduler_job.py:182} INFO - Started process (PID=8675) to work on /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
[2021-03-08 14:48:06,325] {scheduler_job.py:629} INFO - Processing file /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py for tasks to queue
[2021-03-08 14:48:06,326] {logging_mixin.py:104} INFO - [2021-03-08 14:48:06,326] {dagbag.py:448} INFO - Filling up the DagBag from /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
[2021-03-08 14:48:06,609] {scheduler_job.py:639} INFO - DAG(s) dict_keys(['extract_standings']) retrieved from /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
[2021-03-08 14:48:06,633] {logging_mixin.py:104} INFO - [2021-03-08 14:48:06,632] {dag.py:1818} INFO - Sync 1 DAGs
[2021-03-08 14:48:06,641] {logging_mixin.py:104} INFO - [2021-03-08 14:48:06,641] {dag.py:2273} INFO - Setting next_dagrun for extract_standings to 2021-01-01T00:00:00+00:00
[2021-03-08 14:48:06,645] {scheduler_job.py:190} INFO - Processing /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py took 0.321 seconds
[2021-03-08 14:48:38,564] {scheduler_job.py:182} INFO - Started process (PID=8683) to work on /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
[2021-03-08 14:48:38,564] {scheduler_job.py:629} INFO - Processing file /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py for tasks to queue
[2021-03-08 14:48:38,565] {logging_mixin.py:104} INFO - [2021-03-08 14:48:38,565] {dagbag.py:448} INFO - Filling up the DagBag from /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
[2021-03-08 14:48:38,815] {scheduler_job.py:639} INFO - DAG(s) dict_keys(['extract_standings']) retrieved from /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
[2021-03-08 14:48:38,840] {logging_mixin.py:104} INFO - [2021-03-08 14:48:38,840] {dag.py:1818} INFO - Sync 1 DAGs
[2021-03-08 14:48:38,850] {logging_mixin.py:104} INFO - [2021-03-08 14:48:38,849] {dag.py:2273} INFO - Setting next_dagrun for extract_standings to 2021-01-01T00:00:00+00:00
[2021-03-08 14:48:38,854] {scheduler_job.py:190} INFO - Processing /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py took 0.290 seconds
[2021-03-08 14:49:10,274] {scheduler_job.py:182} INFO - Started process (PID=8696) to work on /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
[2021-03-08 14:49:10,274] {scheduler_job.py:629} INFO - Processing file /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py for tasks to queue
[2021-03-08 14:49:10,275] {logging_mixin.py:104} INFO - [2021-03-08 14:49:10,274] {dagbag.py:448} INFO - Filling up the DagBag from /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
[2021-03-08 14:49:10,520] {scheduler_job.py:639} INFO - DAG(s) dict_keys(['extract_standings']) retrieved from /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
[2021-03-08 14:49:10,544] {logging_mixin.py:104} INFO - [2021-03-08 14:49:10,543] {dag.py:1818} INFO - Sync 1 DAGs
[2021-03-08 14:49:10,552] {logging_mixin.py:104} INFO - [2021-03-08 14:49:10,552] {dag.py:2273} INFO - Setting next_dagrun for extract_standings to 2021-01-01T00:00:00+00:00
[2021-03-08 14:49:10,556] {scheduler_job.py:190} INFO - Processing /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py took 0.283 seconds
[2021-03-08 14:49:42,058] {scheduler_job.py:182} INFO - Started process (PID=8709) to work on /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
[2021-03-08 14:49:42,058] {scheduler_job.py:629} INFO - Processing file /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py for tasks to queue
[2021-03-08 14:49:42,058] {logging_mixin.py:104} INFO - [2021-03-08 14:49:42,058] {dagbag.py:448} INFO - Filling up the DagBag from /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
[2021-03-08 14:49:42,308] {scheduler_job.py:639} INFO - DAG(s) dict_keys(['extract_standings']) retrieved from /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
[2021-03-08 14:49:42,333] {logging_mixin.py:104} INFO - [2021-03-08 14:49:42,332] {dag.py:1818} INFO - Sync 1 DAGs
[2021-03-08 14:49:42,341] {logging_mixin.py:104} INFO - [2021-03-08 14:49:42,341] {dag.py:2273} INFO - Setting next_dagrun for extract_standings to 2021-01-01T00:00:00+00:00
[2021-03-08 14:49:42,345] {scheduler_job.py:190} INFO - Processing /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py took 0.288 seconds
[2021-03-08 14:50:13,783] {scheduler_job.py:182} INFO - Started process (PID=8722) to work on /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
[2021-03-08 14:50:13,783] {scheduler_job.py:629} INFO - Processing file /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py for tasks to queue
[2021-03-08 14:50:13,784] {logging_mixin.py:104} INFO - [2021-03-08 14:50:13,783] {dagbag.py:448} INFO - Filling up the DagBag from /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
[2021-03-08 14:50:14,067] {scheduler_job.py:639} INFO - DAG(s) dict_keys(['extract_standings']) retrieved from /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
[2021-03-08 14:50:14,090] {logging_mixin.py:104} INFO - [2021-03-08 14:50:14,090] {dag.py:1818} INFO - Sync 1 DAGs
[2021-03-08 14:50:14,099] {logging_mixin.py:104} INFO - [2021-03-08 14:50:14,099] {dag.py:2273} INFO - Setting next_dagrun for extract_standings to 2021-01-01T00:00:00+00:00
[2021-03-08 14:50:14,103] {scheduler_job.py:190} INFO - Processing /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py took 0.321 seconds
[2021-03-08 14:50:45,519] {scheduler_job.py:182} INFO - Started process (PID=8739) to work on /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
[2021-03-08 14:50:45,520] {scheduler_job.py:629} INFO - Processing file /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py for tasks to queue
[2021-03-08 14:50:45,520] {logging_mixin.py:104} INFO - [2021-03-08 14:50:45,520] {dagbag.py:448} INFO - Filling up the DagBag from /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
[2021-03-08 14:50:45,761] {scheduler_job.py:639} INFO - DAG(s) dict_keys(['extract_standings']) retrieved from /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
[2021-03-08 14:50:45,786] {logging_mixin.py:104} INFO - [2021-03-08 14:50:45,786] {dag.py:1818} INFO - Sync 1 DAGs
[2021-03-08 14:50:45,795] {logging_mixin.py:104} INFO - [2021-03-08 14:50:45,795] {dag.py:2273} INFO - Setting next_dagrun for extract_standings to 2021-01-01T00:00:00+00:00
[2021-03-08 14:50:45,799] {scheduler_job.py:190} INFO - Processing /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py took 0.280 seconds
[2021-03-08 14:51:17,328] {scheduler_job.py:182} INFO - Started process (PID=8749) to work on /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
[2021-03-08 14:51:17,328] {scheduler_job.py:629} INFO - Processing file /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py for tasks to queue
[2021-03-08 14:51:17,329] {logging_mixin.py:104} INFO - [2021-03-08 14:51:17,328] {dagbag.py:448} INFO - Filling up the DagBag from /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
[2021-03-08 14:51:17,598] {scheduler_job.py:639} INFO - DAG(s) dict_keys(['extract_standings']) retrieved from /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
[2021-03-08 14:51:17,622] {logging_mixin.py:104} INFO - [2021-03-08 14:51:17,622] {dag.py:1818} INFO - Sync 1 DAGs
[2021-03-08 14:51:17,631] {logging_mixin.py:104} INFO - [2021-03-08 14:51:17,631] {dag.py:2273} INFO - Setting next_dagrun for extract_standings to 2021-01-01T00:00:00+00:00
[2021-03-08 14:51:17,635] {scheduler_job.py:190} INFO - Processing /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py took 0.308 seconds
[2021-03-08 14:52:31,895] {scheduler_job.py:182} INFO - Started process (PID=8794) to work on /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
[2021-03-08 14:52:31,895] {scheduler_job.py:629} INFO - Processing file /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py for tasks to queue
[2021-03-08 14:52:31,896] {logging_mixin.py:104} INFO - [2021-03-08 14:52:31,896] {dagbag.py:448} INFO - Filling up the DagBag from /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
[2021-03-08 14:52:32,179] {scheduler_job.py:639} INFO - DAG(s) dict_keys(['extract_standings']) retrieved from /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
[2021-03-08 14:52:32,183] {logging_mixin.py:104} INFO - [2021-03-08 14:52:32,183] {dag.py:1818} INFO - Sync 1 DAGs
[2021-03-08 14:52:32,210] {logging_mixin.py:104} INFO - [2021-03-08 14:52:32,210] {dag.py:2273} INFO - Setting next_dagrun for extract_standings to 2021-01-01T00:00:00+00:00
[2021-03-08 14:52:32,214] {scheduler_job.py:190} INFO - Processing /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py took 0.320 seconds
[2021-03-08 14:53:04,334] {scheduler_job.py:182} INFO - Started process (PID=8809) to work on /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
[2021-03-08 14:53:04,334] {scheduler_job.py:629} INFO - Processing file /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py for tasks to queue
[2021-03-08 14:53:04,334] {logging_mixin.py:104} INFO - [2021-03-08 14:53:04,334] {dagbag.py:448} INFO - Filling up the DagBag from /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
[2021-03-08 14:53:04,635] {scheduler_job.py:639} INFO - DAG(s) dict_keys(['extract_standings']) retrieved from /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
[2021-03-08 14:53:04,660] {logging_mixin.py:104} INFO - [2021-03-08 14:53:04,660] {dag.py:1818} INFO - Sync 1 DAGs
[2021-03-08 14:53:04,669] {logging_mixin.py:104} INFO - [2021-03-08 14:53:04,669] {dag.py:2273} INFO - Setting next_dagrun for extract_standings to 2021-01-01T00:00:00+00:00
[2021-03-08 14:53:04,673] {scheduler_job.py:190} INFO - Processing /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py took 0.341 seconds
[2021-03-08 14:53:37,268] {scheduler_job.py:182} INFO - Started process (PID=8830) to work on /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
[2021-03-08 14:53:37,268] {scheduler_job.py:629} INFO - Processing file /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py for tasks to queue
[2021-03-08 14:53:37,269] {logging_mixin.py:104} INFO - [2021-03-08 14:53:37,269] {dagbag.py:448} INFO - Filling up the DagBag from /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
[2021-03-08 14:53:37,679] {scheduler_job.py:639} INFO - DAG(s) dict_keys(['extract_standings']) retrieved from /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
[2021-03-08 14:53:37,704] {logging_mixin.py:104} INFO - [2021-03-08 14:53:37,703] {dag.py:1818} INFO - Sync 1 DAGs
[2021-03-08 14:53:37,712] {logging_mixin.py:104} INFO - [2021-03-08 14:53:37,712] {dag.py:2273} INFO - Setting next_dagrun for extract_standings to 2021-01-01T00:00:00+00:00
[2021-03-08 14:53:37,716] {scheduler_job.py:190} INFO - Processing /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py took 0.449 seconds
[2021-03-08 14:54:09,188] {scheduler_job.py:182} INFO - Started process (PID=8838) to work on /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
[2021-03-08 14:54:09,188] {scheduler_job.py:629} INFO - Processing file /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py for tasks to queue
[2021-03-08 14:54:09,188] {logging_mixin.py:104} INFO - [2021-03-08 14:54:09,188] {dagbag.py:448} INFO - Filling up the DagBag from /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
[2021-03-08 14:54:09,440] {scheduler_job.py:639} INFO - DAG(s) dict_keys(['extract_standings']) retrieved from /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py
[2021-03-08 14:54:09,463] {logging_mixin.py:104} INFO - [2021-03-08 14:54:09,462] {dag.py:1818} INFO - Sync 1 DAGs
[2021-03-08 14:54:09,471] {logging_mixin.py:104} INFO - [2021-03-08 14:54:09,471] {dag.py:2273} INFO - Setting next_dagrun for extract_standings to 2021-01-01T00:00:00+00:00
[2021-03-08 14:54:09,475] {scheduler_job.py:190} INFO - Processing /Users/garymarmon/PycharmProjects/AWTY-Limitless/DataServerContainer/dags/standings_dag.py took 0.288 seconds
